# Generated by Django 5.2.8 on 2025-11-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('fabricante', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=200)),
                ('validade', models.DateField()),
                ('unidade_medida', models.CharField(choices=[('comprimido', 'Comprimido'), ('ml', 'Mililitro'), ('mg', 'Miligrama'), ('unidade', 'Unidade')], max_length=15)),
                ('criado_em', models.DateTimeField()),
                ('imagem', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=150)),
                ('medico_nome', models.CharField(max_length=150)),
                ('crm_medico', models.CharField(max_length=20)),
                ('data_prescricao', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Receitas',
                'db_table': 'receitas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('farmaceutico', 'Farmacêutico'), ('admin', 'Administrador'), ('tecnico', 'Técnico')], max_length=15)),
                ('criado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('alerta_minimo', models.IntegerField(default=10)),
                ('atualizado_em', models.DateTimeField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.medicamentos')),
            ],
            options={
                'verbose_name_plural': 'Estoque',
                'db_table': 'estoque',
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('quantidade_consumida', models.IntegerField()),
                ('data_registro', models.DateTimeField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.medicamentos')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.receitas')),
            ],
            options={
                'verbose_name_plural': 'Consumo',
                'db_table': 'consumo',
            },
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('quantidade', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.medicamentos')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.receitas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Movimentações',
                'db_table': 'movimentacoes',
            },
        ),
        migrations.CreateModel(
            name='Versoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela_afetada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField()),
                ('alteracao', models.TextField()),
                ('data_alteracao', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Versões',
                'db_table': 'versoes',
            },
        ),
    ]
