# Generated by Django 5.2.8 on 2025-11-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentos',
            old_name='nome',
            new_name='nome_comercial',
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='concentracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='controlado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('solucao', 'Solução'), ('injetavel', 'Injetável'), ('pomada', 'Pomada')], default='comprimido', max_length=50),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='lote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
